workspace = { members = ["arrays_strings_hash_tables", "linked_list"] }
[package]
name = "algoritmos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
